steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/batch_inference:v1', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/batch_inference:v1']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kube/
  - --cluster=project-kube