apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classifier
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
      - name: ml-app
        image: gcr.io/multiclassificationproject/imgwebapp:v1
        ports:
        - containerPort: 8501